[package]
name = "oracle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = "21.4.0"

[dev-dependencies]
soroban-sdk = { version = "21.4.0", features = ["testutils"] }

